### ISSUE TITLE
子域名

### ISSUE THREAD

**Issue by dead5nd** [broken5/ShotsScan#2]
Hello，子域名没有搜索匹配功能吗？好像只能输完整的子域名才看的到，而不是输入主域名就会显示子域名

**Comment by broken5** [comment]
非常抱歉，由于这个项目还处于内部开发测试阶段，GitHub上的只是一个大概框架很多细节上的功能没有完善，后续等整个项目完善了会进行统一更新的

**Comment by dead5nd** [comment]
好的，多谢
